[matfrost-mex]
git-tree-sha1 = "b61d9d5d3450faa12efca586a0605c176fb1fd6f"

    [[matfrost-mex.download]]
    sha256 = "7ddbd67a7e553c816ed3a6987363ae16e00f4e9483afc002af7bb0343259b50e"
    url = "https://github.com/ASML-Labs/MATFrost.jl/releases/download/matfrost-mex-v0.5.0-beta.1/matfrost-mex-v0.5.0-beta.1-win-x64.tar.gz"
